package com.lei123.YSPocketTools.utils

object Avatar_Name {
    /**
     * 获取角色名汉字的集合
     * @return 角色名的集合
     */
    fun GetAvatarName(): Map<String, String> {
        val avatarname: MutableMap<String, String> = HashMap()
        avatarname["Albedo"] = "阿贝多"
        avatarname["Ambor"] = "安柏"
        avatarname["Barbara"] = "芭芭拉"
        avatarname["Beidou"] = "北斗"
        avatarname["Bennett"] = "班尼特"
        avatarname["Chongyun"] = "重云"
        avatarname["Diluc"] = "迪卢克"
        avatarname["Diona"] = "迪奥娜"
        avatarname["Eula"] = "优菈"
        avatarname["Fischl"] = "菲谢尔"
        avatarname["Ganyu"] = "甘雨"
        avatarname["Hutao"] = "胡桃"
        avatarname["Qin"] = "琴"
        avatarname["Kazuha"] = "枫原万叶"
        avatarname["Kaeya"] = "凯亚"
        avatarname["Ayaka"] = "神里绫华"
        avatarname["Keqing"] = "刻晴"
        avatarname["Klee"] = "可莉"
        avatarname["Lisa"] = "丽莎"
        avatarname["Mona"] = "莫娜"
        avatarname["Ningguang"] = "凝光"
        avatarname["Noel"] = "诺艾尔"
        avatarname["Qiqi"] = "七七"
        avatarname["Razor"] = "雷泽"
        avatarname["Rosaria"] = "罗莎莉亚"
        avatarname["Sucrose"] = "砂糖"
        avatarname["Tartaglia"] = "达达利亚"
        avatarname["Venti"] = "温迪"
        avatarname["Xiangling"] = "香菱"
        avatarname["Xiao"] = "魈"
        avatarname["Xingqiu"] = "行秋"
        avatarname["Xinyan"] = "辛焱"
        avatarname["Feiyan"] = "烟绯"
        avatarname["Zhongli"] = "钟离"
        avatarname["Yoimiya"] = "宵宫"
        avatarname["Sayu"] = "早柚"
        avatarname["Shougun"] = "雷电将军"
        avatarname["Aloy"] = "埃洛伊"
        avatarname["Sara"] = "九条裟罗"
        avatarname["Kokomi"] = "珊瑚宫心海"
        avatarname["Tohma"] = "托马"
        avatarname["Gorou"] = "五郎"
        avatarname["Itto"] = "荒泷一斗"
        avatarname["Shenhe"] = "申鹤"
        avatarname["Yunjin"] = "云堇"
        avatarname["Yae"] = "八重"
        avatarname["Ayato"] = "绫人"
        avatarname["Yelan"] = "夜兰"
        avatarname["Shinobu"] = "久岐忍"
        avatarname["Heizo"] = "鹿野院"
        return avatarname
    }

    fun GetAvatarNameHanToPinyin(): Map<String, String> {
        val avatarname: MutableMap<String, String> = HashMap()
        avatarname["阿贝多"] = "albedo"
        avatarname["安柏"] = "ambor"
        avatarname["芭芭拉"] = "barbara"
        avatarname["北斗"] = "beidou"
        avatarname["班尼特"] = "bennett"
        avatarname["重云"] = "chongyun"
        avatarname["迪卢克"] = "diluc"
        avatarname["迪奥娜"] = "diona"
        avatarname["优菈"] = "eula"
        avatarname["菲谢尔"] = "fischl"
        avatarname["甘雨"] = "ganyu"
        avatarname["胡桃"] = "hutao"
        avatarname["琴"] = "qin"
        avatarname["枫原万叶"] = "kazuha"
        avatarname["凯亚"] = "kaeya"
        avatarname["神里绫华"] = "ayaka"
        avatarname["刻晴"] = "keqing"
        avatarname["可莉"] = "klee"
        avatarname["丽莎"] = "lisa"
        avatarname["莫娜"] = "mona"
        avatarname["凝光"] = "ningguang"
        avatarname["诺艾尔"] = "noel"
        avatarname["七七"] = "qiqi"
        avatarname["雷泽"] = "razor"
        avatarname["罗莎莉亚"] = "rosaria"
        avatarname["砂糖"] = "sucrose"
        avatarname["达达利亚"] = "tartaglia"
        avatarname["温迪"] = "venti"
        avatarname["香菱"] = "xiangling"
        avatarname["魈"] = "xiao"
        avatarname["行秋"] = "xingqiu"
        avatarname["辛焱"] = "xinyan"
        avatarname["烟绯"] = "feiyan"
        avatarname["钟离"] = "zhongli"
        avatarname["宵宫"] = "yoimiya"
        avatarname["早柚"] = "sayu"
        avatarname["雷电将军"] = "shougun"
        avatarname["埃洛伊"] = "aloy"
        avatarname["九条裟罗"] = "sara"
        avatarname["珊瑚宫心海"] = "kokomi"
        avatarname["托马"] = "tohma"
        avatarname["五郎"] = "gorou"
        avatarname["荒泷一斗"] = "itto"
        avatarname["申鹤"] = "shenhe"
        avatarname["云堇"] = "yunjin"
        avatarname["八重"] = "yae"
        avatarname["空白"] = "kong"
        avatarname["树脂"] = "shuzhi"
        avatarname["绫人"] = "ayato"
        avatarname["夜兰"] = "yelan"
        avatarname["久岐忍"] = "shinobu"
        avatarname["鹿野院"] = "heizo"
        return avatarname
    }
}